load("@rules_cc//cc:defs.bzl", "cc_binary")
load("@io_bazel_rules_go//go:def.bzl", "go_binary")

go_binary(
    name = "hello-go",
    srcs = ["hello-world.go"],
)

cc_binary(
    name = "hello-cpp",
    srcs = ["hello-world.cc"],
)
