load("@io_bazel_rules_go//go:def.bzl", "go_binary")

go_binary(
    name = "day01",
    srcs = ["day01.go"],
    deps = ["//utils:stream_reader_go"],
)

go_binary(
    name = "day02",
    srcs = ["day02.go"],
    deps = ["//utils:stream_reader_go"],
)

go_binary(
    name = "day03",
    srcs = ["day03.go"],
    deps = ["//utils:stream_reader_go"],
)

go_binary(
    name = "day04",
    srcs = ["day04.go"],
    deps = ["//utils:stream_reader_go"],
)
