load("@rules_cc//cc:defs.bzl", "cc_binary")
load("@io_bazel_rules_go//go:def.bzl", "go_binary")

cc_binary(
    name = "cpp",
    srcs = ["main.cc"],
)

go_binary(
    name = "go",
    srcs = ["main.go"],
)
