load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "day01",
    srcs = ["day01.cc"],
    deps = ["//utils:file_reader_cc"],
)

cc_binary(
    name = "day02",
    srcs = ["day02.cc"],
    deps = ["//utils:file_reader_cc"],
)
