load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "day01",
    srcs = ["day01.cc"],
)

cc_binary(
    name = "day02",
    srcs = ["day02.cc"],
)

cc_binary(
    name = "day03",
    srcs = ["day03.cc"],
)
