load("@io_bazel_rules_go//go:def.bzl", "go_binary")

go_binary(
    name = "day01",
    srcs = ["day01.go"],
    deps = ["//utils:stream_read"],
)

go_binary(
    name = "day02",
    srcs = ["day02.go"],
    deps = ["//utils:stream_read"],
)
