load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_test")

go_binary(
    name = "day01",
    srcs = ["day01.go"],
    deps = ["//utils:stream_reader_go"],
)

go_binary(
    name = "day02",
    srcs = ["day02.go"],
    deps = ["//utils:stream_reader_go"],
)

go_binary(
    name = "day03",
    srcs = ["day03.go"],
    deps = ["//utils:stream_reader_go"],
)

go_binary(
    name = "day04",
    srcs = ["day04.go"],
    deps = ["//utils:stream_reader_go"],
)

go_binary(
    name = "day05",
    srcs = ["day05.go"],
    deps = ["//utils:stream_reader_go"],
)

go_binary(
    name = "day06",
    srcs = ["day06.go"],
    deps = ["//utils:stream_reader_go"],
)

go_binary(
    name = "day07",
    srcs = ["day07.go"],
    deps = ["//utils:stream_reader_go"],
)

go_binary(
    name = "day08",
    srcs = ["day08.go"],
)

go_binary(
    name = "day09",
    srcs = ["day09.go"],
    deps = ["//utils:stream_reader_go"],
)

go_binary(
    name = "day10",
    srcs = ["day10.go"],
    deps = ["//utils:stream_reader_go"],
)

go_binary(
    name = "day11",
    srcs = ["day11.go"],
    deps = ["//utils:stream_reader_go"],
)

go_binary(
    name = "day12",
    srcs = ["day12.go"],
    deps = ["//utils:stream_reader_go"],
)

go_binary(
    name = "day13",
    srcs = ["day13.go"],
    deps = ["//utils:stream_reader_go"],
)

go_binary(
    name = "day14_slice",
    srcs = ["day14_slice.go"],
    deps = ["//utils:stream_reader_go"],
)

go_binary(
    name = "day14_linked",
    srcs = ["day14_linked.go"],
    deps = ["//utils:stream_reader_go"],
)

go_binary(
    name = "day14_map",
    srcs = ["day14_map.go"],
    deps = ["//utils:stream_reader_go"],
)

go_binary(
    name = "day15",
    srcs = [
        "day15.go",
        "day15_pq.go",
    ],
    deps = ["//utils:stream_reader_go"],
)

go_binary(
    name = "day16",
    srcs = [
        "day16.go",
        "day16_bits.go",
        "day16_bits_reader.go",
    ],
    deps = ["//utils:stream_reader_go"],
)

go_binary(
    name = "day17",
    srcs = ["day17.go"],
    deps = ["//utils:stream_reader_go"],
)

go_binary(
    name = "day18",
    srcs = ["day18.go"],
    deps = ["//utils:stream_reader_go"],
)

go_test(
    name = "day18_test",
    srcs = [
        "day18.go",
        "day18_test.go",
    ],
    deps = ["//utils:stream_reader_go"],
)
