load("@io_bazel_rules_go//go:def.bzl", "go_binary")

go_binary(
    name = "slice",
    srcs = ["slice.go"],
)

go_binary(
    name = "linked",
    srcs = ["linked.go"],
)

go_binary(
    name = "map",
    srcs = ["map.go"],
)
